### PR TITLE
Show third pillar transfer amounts in correct units

### PR DESCRIPTION
**Pull request by labidas**
Before:
image

After:
image

### CODE REVIEW

**Review by ErkoRisthein — APPROVED** [review]
Nice!

**Comment by ErkoRisthein** [comment]
Maybe also fix the floating-point math issue (`...000000001%` ending) with 2nd pillar percentages:
```
`${(amount * 100).toFixed(2)}%`
```
Or even better, use the `<Percentage value={amount} />` component for that.

**Comment by ErkoRisthein** [comment]
Also, 
```
`${amount}`
``` 
can be simplified to just 
```
amount
```

**Comment by labidas** [comment]
> Maybe also fix the floating-point math issue (`...000000001%` ending) with 2nd pillar percentages:
> 
> ```
> `${(amount * 100).toFixed(2)}%`
> ```
> 
> Or even better, use the `<Percentage value={amount} />` component for that.

Implemented the idea, ty

**Pull request merged**
